### ISSUE TITLE
can't set exposure time of depth sensor on Windows...

### ISSUE THREAD

**Issue by drhalftone** [Vzense/NebulaSDK#1]
The VzExposureTimeParams has a member called mode.  The header file for types says:

typedef struct
{
    VzExposureControlMode mode;
    int	exposureTime;              //When the control mode is AE,  exposureTime represents the maximum exposure time.
                                   //When the control mode is Manual, exposureTime represents the current exposure time.
                                   //When the control mode is Max, exposureTime represents the maximum exposure time allowed at the current frame rate In manual exposure mode.
} VzExposureTimeParams;

while for enums:

typedef enum
{
    VzExposureControlMode_Auto = 0,
    VzExposureControlMode_Manual = 1,
}VzExposureControlMode;

So there is no way to set the exposure time.

**Comment by peter-vzense** [comment]
you could reference the sample code of [RGBResolutionChange](https://github.com/Vzense/NebulaSDK/tree/master/Windows/Samples/Base/DS77C/RGBResolutionChange)
this sample is one demo of changing RGB exposure time, if you want to chane ToF's, you could modify the enum type.

**Comment by peter-vzense** [comment]
> Seeing you example, I am doing it correctly. I think the comments in the header are wrong for the VzExposureTimeParams structure. That being said, I am setting the exposure time before I start the stream, and you do it afterward. So I will make that change to my code. Should I assume that the same is true of the IR gain and the various filtering options?

when you met set exposure fail, did you call it before start stream? I think the key step should be setting manual exposure mode first before call  exposure time changing. Basically, It should be work either call it before or after start stream. 
so if you confirm it related to the sequences, it maybe a bug that we will fix it.

**Comment by drhalftone** [comment]
I tried setting the exposure before and after enabling streaming.  And I did set the exposure mode prior to setting the exposure.  Setting the exposure mode worked.  What happened when I set the exposure to 1500 is that it did change the exposure, but it returned VzRetNoDeviceConnected instead of instead of VzRetOK.  Should the return code be interpreted differently for this function call?

**Comment by peter-vzense** [comment]
we add one new sample that is [ToFExposureTimeSetGet], you could reference it.
